## Computing SG DS Exercise 1 (Bag 1: NUMPY)

Halooo!👋👋👋

Karena hari ini jadwalnya SG DS jadiii pertemuan pertama buat hari ini bakal diganti dengan tugas pemanasan dulu yaa😊

So, untuk exercise pertama bagian 1 ini terdapat 100 pertanyaan soal numpy!

Terdapat beberapa difficulty soal yang kalian akan kerjakan:
- (★☆☆): Easy
- (★★☆): Medium
- (★★★): Hard 

Tapi jangan pusing dulu, kalian tidak perlu mengerjakan semuanya, banyak soal yang kalian kerjakan dari masing-masing difficulty adalah seperti berikut:
- (★☆☆): kerjakan 15 soal
- (★★☆): kerjakan 10 soal
- (★★★): kerjakan 5 soal


### Prerequisite
Sebelum kalian mulai mengerjakan soal, install dulu ya requirements nya.

#### How to install inside the notebook
- jalankan perintah `!pip install -r requirements.txt` di salah satu cell

#### How to install outside the notebook
- jalankan `pip install -r requirements.txt` di terminal

#### Good Practice
- Please use anaconda package instead of only python
- Bikin environment baru khusus untuk SG ini, agar install package nya tidak conflict dengan yang lain


**Kalian tentu akan menemukan jawabannya di repository yang diberikan dibawah atau di google, tapi kita encourage kalian untuk mengerjakan sendiri dulu**


### Disclaimer
You can find the originial repository and author here https://github.com/rougier/numpy-100

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` question number.

In [5]:
!pip3 install -r requirements.txt

You should consider upgrading via the 'python -m pip install --upgrade pip' command.



  Using cached https://files.pythonhosted.org/packages/83/df/0f5dd132200728a86190397e1ea87cd76244e42d39ec5e88efd25b2abd7e/jupyter-1.0.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/c1/35/0479d9707e3c459901a64dd49843b2f06a65a647dc2bcee7b8bfe3560da1/qtconsole-4.7.7-py2.py3-none-any.whl
  Found existing installation: numpy 1.16.2
    Uninstalling numpy-1.16.2:
      Successfully uninstalled numpy-1.16.2
  Found existing installation: pandas 0.25.1
    Uninstalling pandas-0.25.1:
      Successfully uninstalled pandas-0.25.1


In [6]:
!pip3 install mdutils

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [11]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [12]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [13]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
nullvec = np.zeros(10)
nullvec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
nullvec2 = np.zeros(10)
nullvec2[4] = 1
nullvec2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
vec = vec[::-1]
vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
mat3x3 = np.arange(0,9).reshape(3,3)
mat3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
nozero = np.nonzero([1,2,0,0,4,0])
nozero

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [27]:
matiden = np.eye(3)
matiden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
rand3 = np.random.random((3,3,3))
rand3

array([[[0.26699675, 0.49838686, 0.88946518],
        [0.810665  , 0.66103044, 0.50824553],
        [0.66995854, 0.27831262, 0.62577553]],

       [[0.28732712, 0.76521096, 0.38233466],
        [0.07234937, 0.16459193, 0.33118228],
        [0.79357106, 0.89798527, 0.31125914]],

       [[0.85709011, 0.63425757, 0.84140064],
        [0.62806903, 0.17579783, 0.62091386],
        [0.6678422 , 0.81166306, 0.57216442]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
rand10 = np.random.random((10,10))
maxi = np.max(rand10)
mini = np.min(rand10)
rand10, maxi, mini

(array([[0.75842268, 0.05200025, 0.65245798, 0.85592617, 0.60509056,
         0.11130116, 0.51475746, 0.90581684, 0.05820855, 0.4819757 ],
        [0.41365813, 0.29725616, 0.96485158, 0.34379141, 0.28812302,
         0.34284775, 0.70699674, 0.87462979, 0.89784193, 0.22682477],
        [0.31231263, 0.63935699, 0.70663202, 0.19402225, 0.5420745 ,
         0.27345385, 0.28274188, 0.98981322, 0.54543909, 0.87129242],
        [0.13964256, 0.76739972, 0.43611821, 0.89801988, 0.9867845 ,
         0.15372127, 0.43442689, 0.21976099, 0.63968485, 0.62567663],
        [0.35203975, 0.14820726, 0.34725251, 0.57020766, 0.40846827,
         0.72494855, 0.06693507, 0.87647126, 0.00186368, 0.18469911],
        [0.60646731, 0.31716796, 0.03025645, 0.01102173, 0.4681563 ,
         0.99758083, 0.11962727, 0.60055926, 0.6052298 , 0.01593593],
        [0.02049898, 0.06802001, 0.89923497, 0.27485836, 0.83355317,
         0.94126321, 0.07073671, 0.44092586, 0.4491799 , 0.2765746 ],
        [0.99676304, 0.4678

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
rand30 = np.random.random(30)
mean = np.mean(rand30)
mean

0.5314928988640423

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [35]:
mat5x5 = np.random.random((5,5))
mat5x5 = (mat5x5 - np.mean (mat5x5)) / (np.std (mat5x5))
mat5x5

array([[-1.34237447,  1.70946762, -0.44154275,  0.15904203,  1.93681218],
       [-0.30600855,  0.56024723,  1.98871979, -0.72689087,  1.55658345],
       [ 0.23172773, -0.40054906, -1.11050249,  1.54698886, -0.54638612],
       [-0.00583071, -1.1036771 ,  0.18486029, -0.80742829, -0.19011668],
       [ 0.11307812, -0.07356818, -1.04088748, -0.84609366, -1.04567091]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [37]:
array1 = [1,2,3,4,5]
array2 = [4,5,6,7,8]
comm = np.intersect1d(array1,array2)
comm

array([4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [39]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(numpy.datetime64('2020-09-30'),
 numpy.datetime64('2020-10-01'),
 numpy.datetime64('2020-10-02'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [58]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [69]:
mat5x5 = np.zeros((5,5))
mat5x5 += np.arange(5)
mat5x5

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [63]:
ranvec = np.random.random(10)
ranvec.sort()
ranvec

array([0.10455494, 0.14550065, 0.15019332, 0.26090762, 0.26593498,
       0.31029982, 0.45815482, 0.48222065, 0.79177844, 0.79515007])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [45]:
arr = [1,2,3,4,5,6]
np.add.reduce(arr)

21

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [66]:
arr1 = ['saya',7,3,'computing',6.0]
arr2 = ['saya',7,3,'computing',6.0]
np.array_equal(arr1,arr2)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [47]:
imm = np.zeros(5)
imm.flags.writeable = False
imm[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [68]:
rand10 = np.random.random(10)
rand10[rand10.argmax()] = 0
rand10

array([0.72512553, 0.        , 0.39155808, 0.8734207 , 0.30022362,
       0.35176159, 0.52863871, 0.35967378, 0.75660315, 0.29408342])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [49]:
print(arr)

[1, 2, 3, 4, 5, 6]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [50]:
mat3x3_substracted = mat3x3 - mat3x3.mean(axis=1, keepdims=True)
mat3x3_substracted

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [57]:
a = np.random.uniform(0,50,10)
val = 40
a.flat[np.abs(a - val).argmin()]

38.79256465259257

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [85]:
m1 =  [[1,2,3],[11,73,5],[25,2,13]]
m2 =  [[0,1,5],[3,2,6],[5,17,23]]

np.diag(np.dot(m1, m2))

array([ 21, 242, 436])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [93]:
A = np.arange(9).reshape(3,3)
print(A)
A[[1,2]] = A[[2,1]]
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]
 [3 4 5]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [76]:
floatarr = np.random.uniform(-1.0,1.0,10)
np.negative(floatarr, out=floatarr)

array([-0.33777286, -0.35678863,  0.35350182, -0.32919568, -0.82052963,
       -0.45592442,  0.81974405, -0.75865993, -0.32805237,  0.00629507])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [86]:
# Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
# divide = np.root(Z.length())
# R = Z.reshape()

AttributeError: 'list' object has no attribute 'reshape'

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [82]:
intarr = np.random.randint(0,10,15)
np.bincount(intarr).argmax()

6

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [87]:
Z = np.arange(100)
np.random.shuffle(Z)
n = np.random.randint(0,100)

n, Z[np.argsort(Z)[-n:]]

(35,
 array([65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]))

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)